services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:5000"  
    environment:
      FLASK_DEBUG: "1"
    restart: on-failure
    depends_on:
      - redis

  redis:
    image: redis:alpine
